import { ThemeProvider } from "next-themes";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "../components/shared/header";
import Footer from "../components/shared/footer";
import PageTransition from "../components/shared/page-transition";

import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider defaultTheme="light" attribute="class">
          <PageTransition>
            <Header />
            {children}
            <Footer />
          </PageTransition>
        </ThemeProvider>
      </body>
    </html>
  );
}
